// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usercenter

import (
	"github.com/dawn303/cc/internal/pkg/bootstrap"
	"github.com/dawn303/cc/internal/usercenter/biz"
	"github.com/dawn303/cc/internal/usercenter/server"
	"github.com/dawn303/cc/internal/usercenter/service"
	"github.com/dawn303/cc/internal/usercenter/store"
	"github.com/dawn303/cc/pkg/db"
	"github.com/dawn303/cc/pkg/options"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

func wireApp(appInfo bootstrap.AppInfo, config *server.Config, mySQLOptions *db.MySQLOptions, jwtOptions *options.JWTOptions) (*kratos.App, func(), error) {
	logger := bootstrap.NewLogger(appInfo)
	appConfig := bootstrap.AppConfig{
		Info:   appInfo,
		Logger: logger,
	}
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, nil, err
	}
	datastore := store.NewStore(gormDB)
	authenticator, cleanup, err := NewAuthenticator(jwtOptions)
	if err != nil {
		return nil, nil, err
	}
	bizBiz := biz.NewBiz(datastore, authenticator)
	userCenterService := service.NewUserCenterService(bizBiz)
	v := server.NewMiddlewares(logger, authenticator)
	httpServer := server.NewHTTPServer(config, userCenterService, v)
	v2 := server.NewServers(httpServer)
	app := bootstrap.NewApp(appConfig, v2...)
	return app, func() {
		cleanup()
	}, nil
}
